In [1]:
import keras

Using TensorFlow backend.


In [2]:
import keras
from keras.datasets import cifar10

In [4]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

shrink_data = True
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

if shrink_data:
    selected_classes = [0, 1, 2, 3, 4]
    print('train\n', x_train.shape, y_train.shape)
    x = [ex for ex, ey in zip(x_train, y_train) if ey in selected_classes]
    y = [ey for ex, ey in zip(x_train, y_train) if ey in selected_classes]
    x_train = np.stack(x)
    y_train = np.stack(y).reshape(-1,1)
    print(x_train.shape, y_train.shape)

    print('test\n', x_test.shape, y_test.shape)
    x = [ex for ex, ey in zip(x_test, y_test) if ey in selected_classes]
    y = [ey for ex, ey in zip(x_test, y_test) if ey in selected_classes]
    x_test = np.stack(x)
    y_test = np.stack(y).reshape(-1,1)
    print(x_test.shape, y_test.shape)
    num_classes = len(selected_classes)
else:
    print('train\n', x_train.shape, y_train.shape)
    print('test\n', x_test.shape, y_test.shape)
    num_classes = 10

train
 (50000, 32, 32, 3) (50000, 1)
(25000, 32, 32, 3) (25000, 1)
test
 (10000, 32, 32, 3) (10000, 1)
(5000, 32, 32, 3) (5000, 1)


In [7]:
print(x_train.astype('float32'))

[[[[  28.   25.   10.]
   [  37.   34.   19.]
   [  38.   35.   20.]
   ..., 
   [  76.   67.   39.]
   [  81.   72.   43.]
   [  85.   76.   47.]]

  [[  33.   28.   13.]
   [  34.   30.   14.]
   [  32.   27.   12.]
   ..., 
   [  95.   82.   55.]
   [  96.   82.   56.]
   [  85.   72.   45.]]

  [[  39.   32.   15.]
   [  40.   33.   17.]
   [  57.   50.   33.]
   ..., 
   [  93.   76.   52.]
   [ 107.   89.   66.]
   [  95.   77.   54.]]

  ..., 
  [[  83.   73.   52.]
   [  87.   77.   56.]
   [  84.   74.   52.]
   ..., 
   [  99.   93.   70.]
   [  90.   84.   61.]
   [  81.   75.   52.]]

  [[  88.   72.   51.]
   [  90.   74.   52.]
   [  93.   77.   56.]
   ..., 
   [  80.   74.   53.]
   [  76.   70.   49.]
   [  82.   76.   55.]]

  [[  97.   78.   56.]
   [  94.   75.   53.]
   [  93.   75.   53.]
   ..., 
   [  54.   47.   28.]
   [  63.   56.   37.]
   [  72.   65.   46.]]]


 [[[ 170.  180.  198.]
   [ 168.  178.  196.]
   [ 177.  185.  203.]
   ..., 
   [ 162.  179.  2